### ISSUE TITLE
CSV_XS not thread safe

### ISSUE THREAD

**Issue by Tux** [tomk3003/spreadsheet-compare#1]
https://github.com/tomk3003/spreadsheet-compare/blob/317cba5be34ebb16f5325fc06abc8dcec62af8bf/script/spreadcomp#L109

Not an issue yet in Text::CSV_XS?
Do you have example code so I can try to make it thread-safe?

Sorry to hijack an issue to ask

**Comment by tomk3003** [comment]
I just use threading under Windows with Mojo::IOLoop::Thread and had failing tests that went away when using Text::CSV::PP.
The I read [RT #119312](https://rt.cpan.org/Public/Bug/Display.html?id=119312) and decided to wait for a fix for that.

I'll try to come up with a small example showing the problem. But it will take a day or two.

**Comment by tomk3003** [comment]
converting to discussion
